# Generated by Django 5.2.5 on 2025-09-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='lectures/', verbose_name='تصویر')),
                ('content', models.TextField(verbose_name='محتوای کامل')),
                ('teaser', models.TextField(max_length=300, verbose_name='متن کوتاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سرویس')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='services/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name=' ویدیو')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='شاهین', max_length=100, verbose_name='نام سایت')),
                ('site_description', models.TextField(default='خدمات حرفه\u200cای خودرو  ', verbose_name='توضیحات سایت')),
                ('phone', models.CharField(default='+989126098606', max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(default='info@shahin-auto.com', max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(default='کرج، ایران', verbose_name='آدرس')),
                ('instagram_url', models.URLField(default='https://instagram.com/shahinautoservice', verbose_name='لینک اینستاگرام')),
                ('hero_image', models.ImageField(default='site/hero.jpg', upload_to='site/', verbose_name='تصویر اصلی')),
                ('hero_video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدیو تبلیغاتی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
