# Generated by Django 5.2.5 on 2025-09-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='video_url',
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/', verbose_name='ویدیو (MP4)'),
        ),
    ]
