# Generated by Django 5.2.6 on 2025-09-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointmentrequest_servicecategory_service_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bing_site_verification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bing Site Verification'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Facebook Pixel ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Site Verification'),
        ),
    ]
