# Generated by Django 5.2.6 on 2025-09-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesettings_bing_site_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='حداکثر قیمت (تومان)'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='حداقل قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ثابت (تومان) - اختیاری'),
        ),
    ]
