# Generated by Django 5.2.6 on 2025-09-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service_max_price_service_min_price_and_more'),
    ]

    operations = [
    ]
