# Generated by Django 5.2.6 on 2025-09-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20250928_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('car_model', models.CharField(max_length=120, verbose_name='مدل خودرو')),
                ('car_year', models.CharField(blank=True, max_length=10, verbose_name='سال تولید')),
                ('car_plate', models.CharField(blank=True, max_length=20, verbose_name='شماره پلاک')),
                ('appointment_date', models.DateField(verbose_name='تاریخ نوبت')),
                ('appointment_time', models.TimeField(verbose_name='ساعت نوبت')),
                ('message', models.TextField(blank=True, verbose_name='توضیحات اضافی')),
                ('estimated_duration', models.CharField(blank=True, max_length=50, verbose_name='مدت زمان تخمینی')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت تخمینی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_processed', models.BooleanField(default=False, verbose_name='پیگیری شده')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
