# Generated by Django 5.2.6 on 2025-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_lecture_image_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='image',
            field=models.ImageField(upload_to='static/media/bonus/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/lectures/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/services/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/media/services/videos/', verbose_name='ویدیو (MP4)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(default='static/media/site/hero.jpg', upload_to='static/media/site/', verbose_name='تصویر اصلی'),
        ),
    ]
