# Generated by Django 5.2.6 on 2025-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bonus_image_alter_lecture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='image',
            field=models.ImageField(upload_to='bonus/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/', verbose_name='ویدیو (MP4)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(default='site/hero.jpg', upload_to='site/', verbose_name='تصویر اصلی'),
        ),
    ]
