# Generated by Django 6.0 on 2026-01-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_hero_video_file_and_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ویدیو تبلیغاتی (YouTube/Vimeo)'),
        ),
    ]
